# LUMI-G environment $MY_SLURM_* comes from .bashrc
export SLURM_ACCOUNT=$MY_SLURM_ACCOUNT
export SLURM_PARTITION=$MY_SLURM_PARTITION_G
export SLURM_RESERVATION=$MY_SLURM_RESERVATION_G

export SBATCH_ACCOUNT=${SLURM_ACCOUNT}
export SBATCH_PARTITION=${SLURM_PARTITION}

export SALLOC_ACCOUNT=${SLURM_ACCOUNT}
export SALLOC_PARTITION=${SLURM_PARTITION}

if [ -n "${SLURM_RESERVATION}" ]; then
    export SBATCH_RESERVATION=${SLURM_RESERVATION}
    export SALLOC_RESERVATION=${SLURM_RESERVATION}
fi
